### ISSUE TITLE
Tracking Error

### ISSUE THREAD

**Issue by apachexampp** [grokys/gong-shell#3]
How do I get errors with the GongShell. Errors come just about this library and cause crashes whole program.

**Comment by grokys** [comment]
Hi @apachexampp - could you provide more details? A repro would be most useful, but otherwise at least a description of the actual error would be useful.

**Comment by apachexampp** [comment]
Microsoft .NET Framework - JIT

> You can not access the deleted object.
> Facility Name: 'TreeView'.
> in GongSolutions.Shell.ShellTreeView.RefreshItem(TreeNode node)
> in GongSolutions.Shell.ShellTreeView.m_ShellListener_ItemUpdated(Object sender, ShellItemEventArgs e)
> in GongSolutions.Shell.ShellNotificationListener.NotificationWindow.WndProc(Message& m)

**Comment by grokys** [comment]
Hmm, that doesn't tell me enough to diagnose the problem I'm afraid, and I've never seen that error before.

Could you perhaps create a minimal project that reproduces the error and upload it to GitHub?

**Comment by apachexampp** [comment]
I checked and problem is in another part of the code than the library :) Thank you for a great library and sorry for the problem.
